Add "sources" option support for library.
c3lang/c3c pull request #1631
Opened 2024-11-18 16:37 UTC by NexushasTaken

Currently, files in libraries must be in the root folder next to the manifest.json.
This is cumbersome when organizing the files in this folder.  

Although, library system still in early alpha, but still, adding this feature would be great.

2024-11-22 21:40 UTC, lerno requested changes
Please have a look at those 2 minor changes.

2024-11-22 21:40 UTC, lerno commented on src/build/libraries.c
> +		{"sources", "Paths to library sources for targets."},
Maybe add: "such as interface files"

2024-11-22 21:40 UTC, lerno commented on src/build/libraries.c
> +		} else {
Can you update the brace style to match the surrounding code?

2024-11-23 16:17 UTC, NexushasTaken commented on src/build/libraries.c
> +		{"sources", "Paths to library sources for targets."},
Done.

2024-11-23 16:17 UTC, NexushasTaken commented on src/build/libraries.c
> +		} else {
Done.

2024-11-23 23:45 UTC, lerno commented
Oh, I forgot – can you add a note in the releasenotes.md as well?

2024-11-24 09:45 UTC, NexushasTaken commented
Apologies i made a mistake rebasing, but I’ve fixed it right away.

but, I've added the changes to `releasenotes.md`

2024-11-24 14:37 UTC, merged

2024-11-24 14:37 UTC, lerno commented
Thank you!